---

name: "Linting"
on:
  - push

jobs:
  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v1
        with:
          python-version: '3.13'

      - name: "Install OS dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing libxmlsec1-dev pkg-config

      - name: "Install Poetry"
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: "Restore any cached Poetry dependencies"
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: "Install any new dependencies"
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: "Run Black"
        run: poetry run black --quiet --check website

      - name: "Run flake8"
        run: >-
          poetry run
          flake8
          --exclude="migrations,website/tosti/settings/*.py"
          --max-line-length=119
          website

      - name: "Run PyDocStyle"
        run: poetry run pydocstyle --explain --add-ignore=D100,D104 --match-dir='(?!sp)(?!migrations).*'
