---

name: "Testing"
on:
  - push

jobs:
  build:
    name: "Testing"
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v1
        with:
          python-version: '3.13'

      - name: "Install OS dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing libxmlsec1-dev pkg-config

      - name: "Install Poetry"
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: "Restore any cached Poetry dependencies"
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: "Install any new dependencies"
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: "Test migrations"
        run: |
          poetry run python website/manage.py makemigrations --no-input --check --dry-run

      - name: "Perform Django self-check"
        run: |
          poetry run python3 website/manage.py check

      - name: "Run Django tests using Coverage"
        run: poetry run coverage run website/manage.py test website/

      - name: "Check Coverage report"
        run: poetry run coverage report --omit "*/site-packages/*,*/migrations/*"
